### ISSUE TITLE
[H/W PART] Relay module research for electricity control

### ISSUE THREAD

**Issue by othellowhite** [MyHappyHog/ProjectPrototype#8]
Relay module research for electricity control

**Comment by kiriung** [comment]
concern the jumper socket
check it is high or low

check this URL -> http://www.hobbyist.co.nz/?q=interfacing-relay-modules-to-arduino

![kakaotalk_20150914_213724838](https://cloud.githubusercontent.com/assets/12122748/9849776/dd182656-5b28-11e5-8e60-b9ff048f4f9d.jpg)
![kakaotalk_20150914_213725357](https://cloud.githubusercontent.com/assets/12122748/9849778/de36a350-5b28-11e5-9e76-cb28e141090f.jpg)

upper picture is right example(check all jumper socket is on high)
lower picture is about wrong example(first relay module doesn't work because jumper socket is on low)
